// File generated by FlutterFire CLI.
// Modified to use --dart-define environment variables for security.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Build with:
/// ```bash
/// flutter run -d chrome \
///   --dart-define=FIREBASE_WEB_API_KEY=... \
///   --dart-define=FIREBASE_WEB_APP_ID=... \
///   --dart-define=FIREBASE_MESSAGING_SENDER_ID=... \
///   --dart-define=FIREBASE_PROJECT_ID=... \
///   --dart-define=FIREBASE_AUTH_DOMAIN=... \
///   --dart-define=FIREBASE_STORAGE_BUCKET=... \
///   --dart-define=FIREBASE_MEASUREMENT_ID=...
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ── Web: reads from --dart-define with fallback ──
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_WEB_API_KEY',
      defaultValue: 'AIzaSyCMgSX4FLhz5iphD_ftsBSsYBVND4XZGww',
    ),
    appId: String.fromEnvironment(
      'FIREBASE_WEB_APP_ID',
      defaultValue: '1:620720326477:web:8e2751e1cd3d7ade10d904',
    ),
    messagingSenderId: String.fromEnvironment(
      'FIREBASE_MESSAGING_SENDER_ID',
      defaultValue: '620720326477',
    ),
    projectId: String.fromEnvironment(
      'FIREBASE_PROJECT_ID',
      defaultValue: 'storm-cafe-15279',
    ),
    authDomain: String.fromEnvironment(
      'FIREBASE_AUTH_DOMAIN',
      defaultValue: 'storm-cafe-15279.firebaseapp.com',
    ),
    storageBucket: String.fromEnvironment(
      'FIREBASE_STORAGE_BUCKET',
      defaultValue: 'storm-cafe-15279.firebasestorage.app',
    ),
    measurementId: String.fromEnvironment(
      'FIREBASE_MEASUREMENT_ID',
      defaultValue: 'G-1D5VMKPNED',
    ),
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_ANDROID_API_KEY',
      defaultValue: 'AIzaSyBOWcKNQkCtiaZKtSg1-I2qyP9XJgZV4DE',
    ),
    appId: '1:620720326477:android:fc7b91a0d1e1e82b10d904',
    messagingSenderId: '620720326477',
    projectId: 'storm-cafe-15279',
    storageBucket: 'storm-cafe-15279.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_IOS_API_KEY',
      defaultValue: 'AIzaSyAT1EAgmeMUV8DHhoNYw1Uv0NtY0DXesCk',
    ),
    appId: '1:620720326477:ios:ab9498feb68d761a10d904',
    messagingSenderId: '620720326477',
    projectId: 'storm-cafe-15279',
    storageBucket: 'storm-cafe-15279.firebasestorage.app',
    iosBundleId: 'com.example.stormCafeWepapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_IOS_API_KEY',
      defaultValue: 'AIzaSyAT1EAgmeMUV8DHhoNYw1Uv0NtY0DXesCk',
    ),
    appId: '1:620720326477:ios:ab9498feb68d761a10d904',
    messagingSenderId: '620720326477',
    projectId: 'storm-cafe-15279',
    storageBucket: 'storm-cafe-15279.firebasestorage.app',
    iosBundleId: 'com.example.stormCafeWepapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: String.fromEnvironment(
      'FIREBASE_WEB_API_KEY',
      defaultValue: 'AIzaSyCMgSX4FLhz5iphD_ftsBSsYBVND4XZGww',
    ),
    appId: '1:620720326477:web:6b145e4a99cf9ec210d904',
    messagingSenderId: '620720326477',
    projectId: 'storm-cafe-15279',
    authDomain: 'storm-cafe-15279.firebaseapp.com',
    storageBucket: 'storm-cafe-15279.firebasestorage.app',
    measurementId: 'G-KG52VZ78JP',
  );
}
